-- DOUBT ON TCL 
-- https://chatgpt.com/share/684afbf6-cc68-8008-a3a9-aa04737bec61

CREATE DATABASE DBT;
USE DBT;
CREATE TABLE STUDENTS (S_ID INT, S_NAME VARCHAR(25),S_MARKS INT);
INSERT INTO STUDENTS VALUES (101,'ALEX',55),
(102,'STEVE',60),
(103,'TOKYO',70),
(104,'BILL',80),
(105,'TOM',90),
(106,'KUREV',56),
(107,'STARK',94),
(108,'MARK',78),
(109,'JOHN',88),
(110,'GILL',48);
SELECT * FROM STUDENTS;
SET SQL_SAFE_UPDATES = 0;

-- ALTER THE TABLE AND USING THE TCL COMMIT AND ROLLBACK

ALTER TABLE STUDENTS ADD SCHOOL VARCHAR(25);
SELECT * FROM STUDENTS;
-- START A TRANSACTION
START TRANSACTION;
UPDATE STUDENTS SET SCHOOL = 'BSRKV';
ROLLBACK;
SELECT * FROM STUDENTS;

-- VIEWING THE TABLE BEFORE THE ROLLBACK
START TRANSACTION;
UPDATE STUDENTS SET SCHOOL = 'BSRKV';
SELECT * FROM STUDENTS;
ROLLBACK;
SELECT * FROM STUDENTS;

-- DELETE THE ROW NAMED STEVE
START TRANSACTION;
DELETE FROM STUDENTS WHERE S_NAME='STEVE';
ROLLBACK;
SELECT * FROM STUDENTS;

-- DELETE THE ROW NAMED STEVE VIEWING THE TABLE BEFORE ONLY
START TRANSACTION;
DELETE FROM STUDENTS WHERE S_NAME='STEVE';
SELECT * FROM STUDENTS;
ROLLBACK;
SELECT * FROM STUDENTS;

